{% set name = "google-adk" %}
{% set version = "1.1.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/google_adk-{{ version }}.tar.gz
  sha256: 9418675574d2e9fd8a3c8e423186b86fe4ad3f211dd5da400cf24f1ef39fe2d7

build:
  noarch: python
  entry_points:
    - adk = google.adk.cli:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.8,<4
    - pip
  run:
    - python >={{ python_min }}
    - authlib >=1.5.1
    - click >=8.1.8
    - fastapi >=0.115.0
    - google-api-python-client >=2.157.0
    - google-cloud-aiplatform >=1.87.0
    - google-cloud-secret-manager >=2.22.0
    - google-cloud-speech >=2.30.0
    - google-cloud-storage >=2.18.0,<3.0.0
    - google-genai >=1.14.0
    - python-graphviz >=0.20.2
    - mcp >=1.5.0
    - opentelemetry-api >=1.31.0
    - opentelemetry-exporter-gcp-trace >=1.9.0
    - opentelemetry-sdk >=1.31.0
    - pydantic >=2.0,<3.0.0
    - python-dotenv >=1.0.0
    - pyyaml >=6.0.2
    - sqlalchemy >=2.0
    - tzlocal >=5.3
    - uvicorn >=0.34.0

test:
  imports:
    - google.adk
  commands:
    - pip check
    - adk --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Agent Development Kit
  home: https://github.com/google/adk-python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
