{% set name = "google-adk" %}
{% set version = "1.13.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/google_adk-{{ version }}.tar.gz
  sha256: a305d2c83031dc8582cb17088b26b19efdb9c81894bc61ddaab95e5690d8196a

build:
  noarch: python
  entry_points:
    - adk = google.adk.cli:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.8,<4
    - pip
  run:
    - sqlalchemy-spanner >=1.14.0
    - google-cloud-bigtable >=2.32.0
    - google-cloud-spanner >=3.56.0,<4.0.0
    - absolufy-imports >=0.3.1,<1.0.0
    - tenacity >=8.0.0,<9.0.0
    - watchdog >=6.0.0,<7.0.0
    - python-dateutil >=2.9.0.post0,<3.0.0
    - requests >=2.32.4,<3.0.0
    - starlette >=0.46.2,<1.0.0
    - websockets >=15.0.1,<16.0.0
    - typing_extensions >=4.5,<5
    - python >={{ python_min }}
    - authlib >=1.5.1,<2.0.0
    - click >=8.1.8,<9.0.0
    - fastapi >=0.115.0,<1.0.0
    - google-api-python-client >=2.157.0,<3.0.0
    - google-cloud-aiplatform >=1.95.1,<2.0.0
    - google-cloud-secret-manager >=2.22.0,<3.0.0
    - google-cloud-speech >=2.30.0,<3.0.0
    - google-cloud-storage >=2.18.0,<3.0.0
    - google-genai >=1.21.1,<2.0.0
    - python-graphviz >=0.20.2,<1.0.0
    - mcp >=1.5.0
    - opentelemetry-api >=1.31.0,<2.0.0
    - opentelemetry-exporter-gcp-trace >=1.9.0,<2.0.0
    - opentelemetry-sdk >=1.31.0,<2.0.0
    - pydantic >=2.0,<3.0.0
    - python-dotenv >=1.0.0,<2.0.0
    - pyyaml >=6.0.2,<7.0.0
    - sqlalchemy >=2.0,<3.0.0
    - tzlocal >=5.3,<6.0
    - uvicorn >=0.34.0,<1.0.0

test:
  imports:
    - google.adk
  commands:
    - pip check
    - adk --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Agent Development Kit
  home: https://github.com/google/adk-python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
